"""empty message

Revision ID: 7be8308156dc
Revises: 
Create Date: 2021-12-20 19:46:31.765938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be8308156dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GPIO__types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gpioType', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_GPIO__types_gpioType'), 'GPIO__types', ['gpioType'], unique=True)
    op.create_table('GPIO_connect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('GPIO_NUM', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('GPIO_NUM')
    )
    op.create_index(op.f('ix_GPIO_connect_name'), 'GPIO_connect', ['name'], unique=True)
    op.create_table('global_conf',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('val', sa.String(length=128), nullable=True),
    sa.Column('comment', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_global_conf_key'), 'global_conf', ['key'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_global_conf_key'), table_name='global_conf')
    op.drop_table('global_conf')
    op.drop_index(op.f('ix_GPIO_connect_name'), table_name='GPIO_connect')
    op.drop_table('GPIO_connect')
    op.drop_index(op.f('ix_GPIO__types_gpioType'), table_name='GPIO__types')
    op.drop_table('GPIO__types')
    # ### end Alembic commands ###
