"""empty message

Revision ID: f300b57a37af
Revises: 
Create Date: 2022-01-24 01:27:26.202587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f300b57a37af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GPIO_connect',
    sa.Column('gpio_type', sa.String(length=64), nullable=True),
    sa.Column('gpio_num', sa.Integer(), nullable=False),
    sa.Column('val', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('gpio_num')
    )
    op.create_table('global_conf',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('val', sa.String(length=128), nullable=True),
    sa.Column('comment', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_global_conf_key'), 'global_conf', ['key'], unique=False)
    op.create_table('gpio_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_pin', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.String(length=16), nullable=True),
    sa.Column('condition', sa.String(length=3), nullable=True),
    sa.Column('condition_value', sa.String(length=10), nullable=True),
    sa.Column('action_type', sa.String(length=10), nullable=True),
    sa.Column('action_pin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gpio_types',
    sa.Column('gpioType', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('gpioType')
    )
    op.create_index(op.f('ix_gpio_types_gpioType'), 'gpio_types', ['gpioType'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_gpio_types_gpioType'), table_name='gpio_types')
    op.drop_table('gpio_types')
    op.drop_table('gpio_rules')
    op.drop_index(op.f('ix_global_conf_key'), table_name='global_conf')
    op.drop_table('global_conf')
    op.drop_table('GPIO_connect')
    # ### end Alembic commands ###
